### ISSUE TITLE
Need to split and strip each sentence in get_average_sentence_length

### ISSUE THREAD

**Issue by jmcrey** [KristianSkeie/pwp-capstones#1]
```
def get_average_sentence_length(text):
    text = text.replace('!', '.')
    text = text.replace('?', '.')
    sentences = text.split('.')
    length_all_senteces = 0
    no_of_sentences = 0
    for each_sentence in sentences:
        length_all_senteces += len(each_sentence)
        no_of_sentences += 1
    average_sentence_length = length_all_senteces / no_of_sentences    
    return average_sentence_length
#test of function
print(get_average_sentence_length(murder_note))
```

This function is on the right track! However, in order for this to be 100% correct, we have to make two small changes. First, we have to make sure when we're counting the length of the sentence, we perform a `split()` on that sentence.  As it is now, our function is counting the number of characters in a particular sentence rather than the number of words. So, to fix our function and make sure we are getting the average number of words in a sentence, we can use the `split()` function. 
#### The split() function
Essentially, using the default version of `split()` will separate the string by white spaces. For example, if we have a sentence like `"It's nice to meet you"` and we perform `split()`, the function will output the result: `["It's", "nice", "to", "meet", "you"]`. _P.S. Note that the default version of split does it by any number of white spaces. So even if there are multiple spaces between words, `split()` will be able to account for this._ Here is an example use of this function in this code:

```
...
    for each_sentence in sentences:
        length_all_senteces += len(each_sentence.split())
        no_of_sentences += 1
...
```

Notice the use of `split()` inside the `len()` function. Now, the variable `length_all_sentences` will contain the number of words in the sentence, rather than the number of characters.
#### The strip() function
Second, thing we have to do is realize that when we split sentences by a period, it is possible that some sentences will have a trailing space at the end. For example, consider the following sentence: `"Hello. It's nice to meet you. "`. Notice that the end of the sentence has a trailing space. If we were to perform the `split(".")` operation on this sentence, we would get the following result:

`['Hello', " It's nice to meet you", ' ']`

Notice that at the beginning of the second sentence there is a lingering space; also, notice that at the end of our list there is an empty space (e.g. `" "`). Importantly, the last sentence is not an actual sentence -- it is just an empty space. As such, we need to filter out this non-legitimate sentence from our calculation.

There are many ways to approach this problem, but one of the most flexible ways is using the `strip()` function. The `strip()` function (as a default) removes all the extraneous spaces from the beginning and end of a string. For example, if we ran `temp = " Hello ".strip()`, then temp would just contain the string `"Hello"`. So, if we run `strip()` on a string with only white space, then it will return a string that is equivalent to None (e.g. `''`). Using this, we can add the following code to our for loop:
```
...
   for each_sentence in sentences:
        if each_sentence.strip():
            length_all_senteces += len(each_sentence.split())
            no_of_sentences += 1
...
```
The line `if each_sentence.strip()` will make sure that the sentence contains more than just white spaces -- if the sentence is only white spaces, then the `if` statement will evaluate as `False` and the sentence will be ignored.
#### Putting it all together
Putting both of these together, we get the entire function of:

```
def get_average_sentence_length(text):
    text = text.replace('!', '.')
    text = text.replace('?', '.')
    sentences = text.split('.')
    length_all_senteces = 0
    no_of_sentences = 0
    for each_sentence in sentences:
        if each_sentence.strip():
            length_all_senteces += len(each_sentence.split())
            no_of_sentences += 1
    average_sentence_length = length_all_senteces / no_of_sentences
    return average_sentence_length
```

Again, very close! Just needed a few minor adjustments to get it to work exactly how we want.

**Comment by KristianSkeie** [comment]
OK, get it. The strip-function was useful - when counting words instead of characters. Although - when re-reading the text: it's still not obvious to me that sentence length is counted in number of words. Anyway, thank you for useful tips.
