### ISSUE TITLE
Note that build_frequency_table expects a list, not a string

### ISSUE THREAD

**Issue by jmcrey** [KristianSkeie/pwp-capstones#2]
```
print(build_frequency_table("Now we want to see which words were most frequently used in each of the samples"))
```

I just wanted to point out that the function `build_frequency_table` actually expects a list -- not a string. Specifically, it expects the output of `prepare_text()` because `prepare_text` effectively "normalizes" the data (i.e. makes all data look the same). Particularly, when given the proper input, the `build_frequency_table()` function does give us the proper output. For example, running `print(build_frequency_table(['do', 'you', 'see', 'what', 'i', 'see']))` will output:

`{'do': 1, 'you': 1, 'see': 2, 'what': 1, 'i': 1}`

This is the exact output we expect. So nice job preparing this function! I just wanted to point out the expected input for this function.

_P.S. One thing we can change in the implementation is making use of the `+=` operator when updating an already existing entry. For example, instead of creating a new variable `new_frequency`, we can simply update the data in-place, like so:_

`frequency_table[word] += 1`

_This is just a suggestion, however. Either way will work perfectly fine!_

**Comment by KristianSkeie** [comment]
Yes, I see that now. Unnessecary code, I totally agree.
Thanks, again.
