### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jmcrey** [KristianSkeie/pwp-capstones#3]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 4/4
* _Comment(s):_ Code included runs without any errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4/4
* _Comment(s):_ The code produces the suite of functions and classes required of it and calls them in an appropriate order. Also, the code is well-formatted and follows many of Python's best practices. Great job!
 
### Criteria 3: Software Architecture
* _Score Level:_ 4/4
* _Comment(s):_ The code is separated into distinct functions and classes, each of which are invoked for their own purposes. Further, some of the functions make use of the other functions/classes implemented in the project to achieve their goal. For example, the `find_text_similarity` function uses the `TextSample` object and numerous other functions to achieve its unique goal. Nice job!
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 3/4
* _Comment(s):_ Python language features are usually used, but there are 1-3 occasions where a coded construction could have been accomplished by a Python built-in. For example, the `get_average_sentence_length()` function could have used [the `split()` and `strip()` functions](#1) to achieve its goal. Further, the `build_frequency_table` function could have used the `+=` operator to [update the dictionary entry in place](#2), rather than creating a new variable. However, these are very minor changes. Overall, the code made good use of Python's built-in features. Specifically, the use of `len()` in the `ngram_creator()` function and the use of `replace()` in the `prepare_data()` function was great! 

### Criteria 5: Produces Accurate Output
* _Score Level:_ 2/4
* _Comment(s):_ Unfortunately the code output is inaccurate due to [a small bug](#1) in the `get_average_sentence_length()` function.
 
### Overall Score: 17/20

Overall, this was a very good project! The code was well-formatted, made good use of Python's built-ins, and it often leveraged outside functions to achieve a particular goal. The only major thing I noticed was the bug in the `get_average_sentence_length()` function; but, two small changes and that function would have been perfect. 

Excellent job with this project!

**Comment by KristianSkeie** [comment]
Great, thanks for your review and thorough comments.
I regret now that I did not build in a test for sentence length
